networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  # rsbuild:
  #   image: node:22
  #   hostname: rsbuild
  #   working_dir: /app
  #   environment:
  #     - "PNPM_HOME=/app/node_modules/"
  #     - "PNPM_STORE_PATH=/app/node_modules/.pnpm-store"
  #   command:
  #     - bash
  #     - -c
  #     - >
  #       groupmod -g 41812 node &&
  #       usermod -u 41812 -g 41812 node &&
  #       npm install -g pnpm@latest-10 &&
  #       chown -R 41812:41812 dist node_modules &&
  #       su - node -c "
  #         cd /app &&
  #         set -x &&
  #         pnpm install --store-dir $$PNPM_STORE_PATH &&
  #         pnpm run dev
  #       "
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./:/app
  #     - splunk-app-dist:/app/dist
  #     - pnpm-node-modules:/app/node_modules
  rsbuild:
    image: splunk/splunk:latest
    hostname: rsbuild
    working_dir: /app
    environment:
      - "PNPM_HOME=/app/node_modules/"
      - "PNPM_STORE_PATH=/app/node_modules/.pnpm-store"
    entrypoint: []
    user: root
    command:
      - bash
      - -c
      - >
        chown -R splunk:splunk dist node_modules &&
        sudo -u splunk bash -c "
          curl -fsSL https://get.pnpm.io/install.sh | sh - &&
          export SPLUNK_HOME=/opt/splunk &&
          export PATH=/home/splunk/.local/share/pnpm:/opt/splunk/bin:$$PATH &&
          export NODE_PATH=/opt/splunk/lib/node_modules &&
          export LD_LIBRARY_PATH=/opt/splunk/opt/jemalloc-4k-nostats/lib:/opt/splunk/lib &&
          cd /app && 
          set -x && 
          python3.9 -m venv /home/splunk/rsbuild-venv &&
          source /home/splunk/rsbuild-venv/bin/activate &&
          pnpm install --store-dir $$PNPM_STORE_PATH && 
          pnpm run dev
        "
    ports:
      - 3001:3000
    volumes:
      - ./:/app
      - splunk-app-dist:/app/dist
      - pnpm-node-modules:/app/node_modules

  splunkdev:
    image: splunk/splunk:latest
    hostname: splunk
    environment:
      - "SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com"
      - "SPLUNK_START_ARGS=--accept-license"
      - "SPLUNK_PASSWORD=Temp1234!"
    ports:
      - 8001:8000
      # - 8089:8089
    volumes:
      - splunk-etc:/opt/splunk/etc
      # Change YOUR_APP_ID_HERE to your app ID
      - splunk-app-dist:/opt/splunk/etc/apps/splunk-react18-asgi
      # Uncomment this line to keep app local separate from dist.
      # NOTE! This shouldn't be necessary as rsbuild SHOULD preserve local
      # - splunk-app-local:/opt/splunk/etc/apps/splunk-react18-asgi/local
      # Uncomment out the following line to use a custom Splunk license instead of a trial
      # - ./.dev/splunk.lic:/opt/splunk/etc/licenses/enterprise/splunk.lic

volumes:
  splunk-app-dist: {}
  pnpm-node-modules: {}
  splunk-etc: {}
  splunk-app-local: {}
