[script:splunk_react18_asgi_example]
match                   = /splunk_react18_asgi_example
script                  = splunk_react18_asgi_example.py
script.param            = splunk_react18_asgi_example.app
driver                  = persistconn.py
# capability              = admin_all_objects
scripttype              = persist
requireAuthentication   = true
passPayload             = base64
passHttpHeaders         = true
passHttpCookies         = true